language: generic
os: linux
dist: trusty
jobs:
  include:
    - stage: client
      language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      before_script:
        - npm install -g @angular/cli
        - npm install
      script:
        - pushd ./travis-mul-client
        - ng test --watch=false --no-progress --browsers=ChromeHeadless
        - ng build --prod
        - popd
      workspaces:
        create:
          name: travis-mul-ws-client
          paths: ../

    - stage: api
      language: java
      jdk: oraclejdk8
      git:
        clone: false
      workspaces:
        use: travis-mul-ws-api
      before_script:
        - cd ./travis-mul-api
      script:
        - mvn package -DskipTests
    - stage: docker
      language: generic
      workspaces:
        use: travis-mul-ws-api
      git:
        clone: false
      services:
        - docker
      before_script:
        - cd
      script:
        -
