language: generic
os: linux
dist: trusty
jobs:
  include:
    - stage: client
      language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      before_script:
        - npm install -g @angular/cli
        - npm install
      script:
        - pushd ./travis-mul-client
        - ng test --watch=false --no-progress --browsers=ChromeHeadless
        - ng build --prod
        - popd
      cache: npm
      workspaces:
        create:
          name: travis-mul-ws
          paths: /home/travis/build/ajduet/travis-mult

    - stage: api
      language: java
      jdk: oraclejdk8
      git:
        clone: false
      workspaces:
        use: travis-mul-ws-api
      before_script:
        - cd ./ajduet/travis-mult/travis-mul-api
      script:
        - mvn package -DskipTests
