language: generic
os: linux
dist: trusty
jobs:
  include:
    - stage: client
      language: node_js
      node_js:
        - 10
      addons:
        chrome: stable
      before_script:
        - cd ./travis-mul-client
        - npm install -g @angular/cli
        - npm install
      script:
        - ng test --watch=false --no-progress --browsers=ChromeHeadless
        - ng build --prod
      cache:
        directories:
          - ./dist

    - stage: api
      language: java
      jdk: oraclejdk8
      before_script:
        - cd ./travis-mul-api
      script:
        - mvn package -DskipTests
