jobs:
  include:
    - stage: angular
      language: nodejs
      node_js:
        - 10
      addons:
        chrome: stable
      before_script:
        - cd ./travis-mul-client
        - npm install -g @angular/cli
        - npm install
      script:
        - ng test --watch=false --no-progress --browser=ChromeHeadless
        - ng build --prod
      cache:
        directories:
          - ./
